-- ============================================================================
-- 20260420_breed_predispositions_seed.sql
-- ----------------------------------------------------------------------------
-- Fase 3c do plano vet-grade. Seed inicial de breed_predispositions:
--   - 20 raças de cães (mais populares no Brasil/mundo)
--   - 10 raças de gatos
--   - 3-5 condições por raça, bilíngue (pt/en) + rationale breve
--   - severity = monitor (leve) | watch (relevante) | manage (ativo)
-- Rodar idempotente via ON CONFLICT DO NOTHING.
-- Breeds usam nome formal mais comum em PT-BR; a Edge Function de consulta
-- deve normalizar via LOWER + aliases (ver Fase 3d).
-- ============================================================================

INSERT INTO public.breed_predispositions
  (species, breed, condition_key, condition_pt, condition_en, rationale_pt, rationale_en, severity, source)
VALUES
-- ============================================================
-- CÃES (20 raças)
-- ============================================================

-- 1) Labrador Retriever
('dog','Labrador Retriever','hip_dysplasia','Displasia coxofemoral','Hip dysplasia',
  'Raça grande com predisposição genética; radiografia preventiva após 12 meses.',
  'Large breed with genetic predisposition; screening radiographs after 12 months.',
  'watch','seed'),
('dog','Labrador Retriever','elbow_dysplasia','Displasia de cotovelo','Elbow dysplasia',
  'Comum em raças grandes de crescimento rápido; claudicação de membro anterior.',
  'Common in fast-growing large breeds; forelimb lameness.',
  'watch','seed'),
('dog','Labrador Retriever','obesity','Tendência à obesidade','Obesity tendency',
  'Metabolismo predisposto ao ganho de peso; controle rigoroso de ração.',
  'Metabolic predisposition to weight gain; strict food control needed.',
  'manage','seed'),
('dog','Labrador Retriever','gastric_torsion','Torção gástrica (GDV)','Gastric dilatation-volvulus',
  'Risco em cães de porte grande/peito profundo; evitar exercício pós-refeição.',
  'Risk in large, deep-chested dogs; avoid exercise after meals.',
  'monitor','seed'),

-- 2) Golden Retriever
('dog','Golden Retriever','hip_dysplasia','Displasia coxofemoral','Hip dysplasia',
  'Alta prevalência; triagem PennHIP/OFA recomendada.',
  'High prevalence; PennHIP/OFA screening recommended.',
  'watch','seed'),
('dog','Golden Retriever','hemangiosarcoma','Hemangiossarcoma','Hemangiosarcoma',
  'Incidência muito alta na raça; check-up abdominal em cães idosos.',
  'Very high breed incidence; abdominal check-up in older dogs.',
  'manage','seed'),
('dog','Golden Retriever','lymphoma','Linfoma','Lymphoma',
  'Uma das neoplasias mais comuns da raça; atenção a linfonodos aumentados.',
  'One of the most common neoplasms in the breed; watch for enlarged lymph nodes.',
  'watch','seed'),
('dog','Golden Retriever','hypothyroidism','Hipotireoidismo','Hypothyroidism',
  'Raça predisposta; avaliar T4/TSH em casos de ganho de peso ou letargia.',
  'Predisposed breed; evaluate T4/TSH in cases of weight gain or lethargy.',
  'watch','seed'),

-- 3) Poodle
('dog','Poodle','luxating_patella','Luxação de patela','Patellar luxation',
  'Comum em porodes menores; avaliar claudicação intermitente.',
  'Common in smaller poodles; evaluate intermittent lameness.',
  'watch','seed'),
('dog','Poodle','epilepsy','Epilepsia idiopática','Idiopathic epilepsy',
  'Predisposição hereditária; crises generalizadas geralmente entre 1-5 anos.',
  'Hereditary predisposition; generalized seizures usually between 1-5 years.',
  'monitor','seed'),
('dog','Poodle','progressive_retinal_atrophy','Atrofia progressiva de retina','Progressive retinal atrophy',
  'Causa cegueira gradual; teste genético disponível.',
  'Causes gradual blindness; genetic test available.',
  'watch','seed'),
('dog','Poodle','addisons_disease','Doença de Addison','Addison''s disease',
  'Hipoadrenocorticismo primário; sinais vagos de apatia e vômitos.',
  'Primary hypoadrenocorticism; vague signs of lethargy and vomiting.',
  'monitor','seed'),

-- 4) Shih Tzu
('dog','Shih Tzu','brachycephalic_airway','Síndrome braquicefálica','Brachycephalic airway syndrome',
  'Face achatada causa ronco, estertor e intolerância ao exercício.',
  'Flat face causes snoring, stridor, and exercise intolerance.',
  'manage','seed'),
('dog','Shih Tzu','dry_eye','Ceratoconjuntivite seca','Keratoconjunctivitis sicca (dry eye)',
  'Olhos proeminentes predispõem; teste de Schirmer em consultas de rotina.',
  'Prominent eyes predispose; Schirmer tear test at routine visits.',
  'watch','seed'),
('dog','Shih Tzu','dental_crowding','Apinhamento dentário','Dental crowding',
  'Boca pequena causa aglomeração; escovação diária + profilaxia regular.',
  'Small mouth causes crowding; daily brushing + regular cleaning.',
  'watch','seed'),
('dog','Shih Tzu','intervertebral_disc','Doença do disco intervertebral','Intervertebral disc disease',
  'Corpo alongado aumenta risco; evitar saltos de superfícies altas.',
  'Elongated body increases risk; avoid jumps from high surfaces.',
  'watch','seed'),

-- 5) Yorkshire Terrier
('dog','Yorkshire Terrier','luxating_patella','Luxação de patela','Patellar luxation',
  'Muito comum em raças toy; claudicação de "pulo" intermitente.',
  'Very common in toy breeds; intermittent "skip" lameness.',
  'watch','seed'),
('dog','Yorkshire Terrier','tracheal_collapse','Colapso traqueal','Tracheal collapse',
  'Tosse de ganso característica; usar peitoral em vez de coleira.',
  'Characteristic honking cough; use harness instead of collar.',
  'manage','seed'),
('dog','Yorkshire Terrier','dental_disease','Doença periodontal','Periodontal disease',
  'Raças toy são altamente predispostas; profilaxia anual é essencial.',
  'Toy breeds are highly predisposed; annual dental cleaning essential.',
  'manage','seed'),
('dog','Yorkshire Terrier','portosystemic_shunt','Shunt portossistêmico','Portosystemic shunt',
  'Desvio congênito do sangue portal; sinais neurológicos pós-refeição.',
  'Congenital portal blood bypass; post-meal neurological signs.',
  'monitor','seed'),

-- 6) Maltês
('dog','Maltês','luxating_patella','Luxação de patela','Patellar luxation',
  'Frequente em toy breeds; classificada em graus I-IV.',
  'Frequent in toy breeds; graded I-IV.',
  'watch','seed'),
('dog','Maltês','dental_disease','Doença periodontal','Periodontal disease',
  'Alta prevalência; escovação e profilaxia regulares.',
  'High prevalence; regular brushing and cleaning.',
  'manage','seed'),
('dog','Maltês','juvenile_hypoglycemia','Hipoglicemia juvenil','Juvenile hypoglycemia',
  'Filhotes toy têm baixa reserva de glicogênio; alimentação frequente.',
  'Toy puppies have low glycogen reserves; frequent feeding needed.',
  'monitor','seed'),
('dog','Maltês','tracheal_collapse','Colapso traqueal','Tracheal collapse',
  'Comum em raças toy; evitar coleiras apertadas.',
  'Common in toy breeds; avoid tight collars.',
  'watch','seed'),

-- 7) Bulldog Inglês
('dog','Bulldog Inglês','brachycephalic_airway','Síndrome braquicefálica','Brachycephalic airway syndrome',
  'Grave na raça; pode exigir cirurgia de narinas e palato.',
  'Severe in the breed; may require nares and palate surgery.',
  'manage','seed'),
('dog','Bulldog Inglês','hip_dysplasia','Displasia coxofemoral','Hip dysplasia',
  'Altíssima prevalência; triagem radiográfica recomendada.',
  'Very high prevalence; screening radiographs recommended.',
  'watch','seed'),
('dog','Bulldog Inglês','skin_fold_dermatitis','Dermatite de dobras cutâneas','Skin fold dermatitis',
  'Dobras faciais retêm umidade; limpeza diária com antisséptico.',
  'Facial folds retain moisture; daily antiseptic cleaning.',
  'manage','seed'),
('dog','Bulldog Inglês','cherry_eye','Prolapso da glândula da 3ª pálpebra','Cherry eye',
  'Protrusão da glândula nictitante; correção cirúrgica conservadora.',
  'Nictitating gland protrusion; conservative surgical correction.',
  'watch','seed'),

-- 8) Buldogue Francês
('dog','Buldogue Francês','brachycephalic_airway','Síndrome braquicefálica','Brachycephalic airway syndrome',
  'Face achatada + paladar mole alongado; monitorar esforço respiratório.',
  'Flat face + elongated soft palate; monitor respiratory effort.',
  'manage','seed'),
('dog','Buldogue Francês','intervertebral_disc','Doença do disco intervertebral','Intervertebral disc disease',
  'Raça com alta incidência; atenção a dor súbita e paresia posterior.',
  'Breed with high incidence; watch for sudden pain and hind paresis.',
  'manage','seed'),
('dog','Buldogue Francês','atopic_dermatitis','Dermatite atópica','Atopic dermatitis',
  'Prurido crônico e otites recorrentes; manejo multimodal.',
  'Chronic pruritus and recurrent otitis; multimodal management.',
  'watch','seed'),
('dog','Buldogue Francês','heat_intolerance','Intolerância ao calor','Heat intolerance',
  'Risco de golpe de calor; evitar exercício em dias quentes.',
  'Heat stroke risk; avoid exercise on hot days.',
  'manage','seed'),

-- 9) Pug
('dog','Pug','brachycephalic_airway','Síndrome braquicefálica','Brachycephalic airway syndrome',
  'Clássico na raça; roncos, engasgos e dispneia são alerta.',
  'Classic in the breed; snoring, gagging, and dyspnea are warning signs.',
  'manage','seed'),
('dog','Pug','heat_intolerance','Intolerância ao calor','Heat intolerance',
  'Sistema respiratório comprometido; termorregulação ineficiente.',
  'Compromised respiratory system; inefficient thermoregulation.',
  'manage','seed'),
('dog','Pug','corneal_ulcer','Úlcera de córnea','Corneal ulcer',
  'Olhos proeminentes traumatizam facilmente; procurar vermelhidão e lacrimejamento.',
  'Prominent eyes are easily injured; watch for redness and tearing.',
  'watch','seed'),
('dog','Pug','hip_dysplasia','Displasia coxofemoral','Hip dysplasia',
  'Embora pequena, a raça tem prevalência alta de displasia.',
  'Although small, the breed has high dysplasia prevalence.',
  'watch','seed'),

-- 10) Chihuahua
('dog','Chihuahua','luxating_patella','Luxação de patela','Patellar luxation',
  'Muito frequente; claudicação intermitente de membro posterior.',
  'Very frequent; intermittent hindlimb lameness.',
  'watch','seed'),
('dog','Chihuahua','tracheal_collapse','Colapso traqueal','Tracheal collapse',
  'Anéis traqueais fracos; tosse seca desencadeada por excitação.',
  'Weak tracheal rings; dry cough triggered by excitement.',
  'watch','seed'),
('dog','Chihuahua','hydrocephalus','Hidrocefalia','Hydrocephalus',
  'Fontanela aberta em muitos indivíduos; sinais neurológicos precoces.',
  'Open fontanelle in many individuals; early neurological signs.',
  'monitor','seed'),
('dog','Chihuahua','hypoglycemia','Hipoglicemia em filhotes','Juvenile hypoglycemia',
  'Baixa reserva de glicogênio; alimentação fracionada em filhotes.',
  'Low glycogen reserve; frequent small meals in puppies.',
  'monitor','seed'),

-- 11) Border Collie
('dog','Border Collie','collie_eye_anomaly','Anomalia do olho do Collie','Collie eye anomaly',
  'Defeito congênito de coroide; exame oftálmico em filhotes.',
  'Congenital choroidal defect; ophthalmic exam in puppies.',
  'monitor','seed'),
('dog','Border Collie','hip_dysplasia','Displasia coxofemoral','Hip dysplasia',
  'Predisposição moderada; avaliar em raças ativas de trabalho.',
  'Moderate predisposition; evaluate in active working breeds.',
  'watch','seed'),
('dog','Border Collie','epilepsy','Epilepsia idiopática','Idiopathic epilepsy',
  'Prevalência significativa; primeiras crises geralmente 1-5 anos.',
  'Significant prevalence; first seizures usually 1-5 years.',
  'monitor','seed'),
('dog','Border Collie','mdr1_mutation','Sensibilidade medicamentosa MDR1','MDR1 drug sensitivity',
  'Mutação do gene MDR1 causa reação a ivermectina, loperamida e outros.',
  'MDR1 gene mutation causes reactions to ivermectin, loperamide, and others.',
  'manage','seed'),

-- 12) Pastor Alemão
('dog','Pastor Alemão','hip_dysplasia','Displasia coxofemoral','Hip dysplasia',
  'Uma das raças mais afetadas; triagem obrigatória antes de reprodução.',
  'One of the most affected breeds; screening mandatory before breeding.',
  'manage','seed'),
('dog','Pastor Alemão','elbow_dysplasia','Displasia de cotovelo','Elbow dysplasia',
  'Alta prevalência; claudicação em membro anterior.',
  'High prevalence; forelimb lameness.',
  'watch','seed'),
('dog','Pastor Alemão','gastric_torsion','Torção gástrica (GDV)','Gastric dilatation-volvulus',
  'Peito profundo aumenta risco; gastropexia profilática discutível.',
  'Deep chest increases risk; prophylactic gastropexy debatable.',
  'watch','seed'),
('dog','Pastor Alemão','degenerative_myelopathy','Mielopatia degenerativa','Degenerative myelopathy',
  'Paresia progressiva de membros posteriores em cães idosos.',
  'Progressive hindlimb paresis in older dogs.',
  'monitor','seed'),
('dog','Pastor Alemão','exocrine_pancreatic_insufficiency','Insuficiência pancreática exócrina','Exocrine pancreatic insufficiency',
  'Perda de peso com apetite aumentado e fezes volumosas.',
  'Weight loss with increased appetite and voluminous feces.',
  'monitor','seed'),

-- 13) Rottweiler
('dog','Rottweiler','hip_dysplasia','Displasia coxofemoral','Hip dysplasia',
  'Raça gigante predisposta; triagem radiográfica após 12 meses.',
  'Giant breed predisposed; screening radiographs after 12 months.',
  'watch','seed'),
('dog','Rottweiler','osteosarcoma','Osteossarcoma','Osteosarcoma',
  'Tumor ósseo primário mais comum; claudicação em membro afetado.',
  'Most common primary bone tumor; lameness in affected limb.',
  'manage','seed'),
('dog','Rottweiler','dilated_cardiomyopathy','Cardiomiopatia dilatada','Dilated cardiomyopathy',
  'Avaliação ecocardiográfica em cães idosos.',
  'Echocardiographic evaluation in older dogs.',
  'watch','seed'),
('dog','Rottweiler','aortic_stenosis','Estenose subaórtica','Subaortic stenosis',
  'Sopro cardíaco em filhotes requer investigação ecocardiográfica.',
  'Heart murmur in puppies requires echocardiographic workup.',
  'monitor','seed'),

-- 14) Dachshund
('dog','Dachshund','intervertebral_disc','Doença do disco intervertebral','Intervertebral disc disease',
  'Coluna alongada causa alta incidência; evitar escadas e saltos.',
  'Elongated spine causes high incidence; avoid stairs and jumps.',
  'manage','seed'),
('dog','Dachshund','obesity','Obesidade','Obesity',
  'Agrava risco de IVDD; manejo rigoroso de peso é essencial.',
  'Worsens IVDD risk; strict weight management essential.',
  'manage','seed'),
('dog','Dachshund','dental_disease','Doença periodontal','Periodontal disease',
  'Comum na raça; escovação e profilaxia anuais.',
  'Common in the breed; annual brushing and cleaning.',
  'watch','seed'),
('dog','Dachshund','progressive_retinal_atrophy','Atrofia progressiva de retina','Progressive retinal atrophy',
  'Cegueira noturna progressiva; sem tratamento específico.',
  'Progressive night blindness; no specific treatment.',
  'monitor','seed'),

-- 15) Beagle
('dog','Beagle','epilepsy','Epilepsia idiopática','Idiopathic epilepsy',
  'Comum na raça; manejo com anticonvulsivantes.',
  'Common in the breed; management with anticonvulsants.',
  'monitor','seed'),
('dog','Beagle','hypothyroidism','Hipotireoidismo','Hypothyroidism',
  'Sinais incluem letargia, ganho de peso e alopecia simétrica.',
  'Signs include lethargy, weight gain, and symmetric alopecia.',
  'watch','seed'),
('dog','Beagle','obesity','Obesidade','Obesity',
  'Apetite voraz; controle rigoroso de porções.',
  'Voracious appetite; strict portion control.',
  'manage','seed'),
('dog','Beagle','intervertebral_disc','Doença do disco intervertebral','Intervertebral disc disease',
  'Corpo alongado aumenta risco; atenção a dor súbita.',
  'Elongated body increases risk; watch for sudden pain.',
  'watch','seed'),
('dog','Beagle','glaucoma','Glaucoma','Glaucoma',
  'Pressão intraocular elevada; dor ocular e vermelhidão.',
  'Elevated intraocular pressure; ocular pain and redness.',
  'monitor','seed'),

-- 16) Boxer
('dog','Boxer','boxer_cardiomyopathy','Cardiomiopatia arritmogênica do Boxer (ARVC)','Arrhythmogenic right ventricular cardiomyopathy',
  'Arritmia ventricular; Holter recomendado a partir de 3 anos.',
  'Ventricular arrhythmia; Holter monitoring recommended from age 3.',
  'watch','seed'),
('dog','Boxer','mast_cell_tumor','Tumor de mastócitos','Mast cell tumor',
  'Alta prevalência; qualquer nódulo cutâneo merece PAAF.',
  'High prevalence; any skin nodule warrants FNA.',
  'watch','seed'),
('dog','Boxer','brachycephalic_airway','Síndrome braquicefálica','Brachycephalic airway syndrome',
  'Face moderadamente achatada; sinais respiratórios no esforço.',
  'Moderately flat face; respiratory signs on exertion.',
  'watch','seed'),
('dog','Boxer','hip_dysplasia','Displasia coxofemoral','Hip dysplasia',
  'Predisposição moderada; triagem em cães de trabalho.',
  'Moderate predisposition; screening in working dogs.',
  'watch','seed'),

-- 17) Cocker Spaniel
('dog','Cocker Spaniel','chronic_otitis','Otite externa crônica','Chronic otitis externa',
  'Orelhas pendulares retêm umidade; limpeza regular essencial.',
  'Pendulous ears retain moisture; regular cleaning essential.',
  'manage','seed'),
('dog','Cocker Spaniel','progressive_retinal_atrophy','Atrofia progressiva de retina','Progressive retinal atrophy',
  'Cegueira progressiva; teste genético disponível.',
  'Progressive blindness; genetic test available.',
  'watch','seed'),
('dog','Cocker Spaniel','autoimmune_hemolytic_anemia','Anemia hemolítica imunomediada','Immune-mediated hemolytic anemia',
  'Raça predisposta; fadiga súbita e mucosas pálidas.',
  'Predisposed breed; sudden fatigue and pale mucous membranes.',
  'monitor','seed'),
('dog','Cocker Spaniel','dilated_cardiomyopathy','Cardiomiopatia dilatada','Dilated cardiomyopathy',
  'Monitoramento cardíaco em cães de meia-idade.',
  'Cardiac monitoring in middle-aged dogs.',
  'monitor','seed'),

-- 18) Cavalier King Charles Spaniel
('dog','Cavalier King Charles Spaniel','mitral_valve_disease','Doença da válvula mitral','Mitral valve disease',
  'Altíssima prevalência; ecocardio anual após 5 anos.',
  'Very high prevalence; annual echocardiogram after age 5.',
  'manage','seed'),
('dog','Cavalier King Charles Spaniel','syringomyelia','Siringomielia','Syringomyelia',
  'Cavidades na medula cervical; coçar o ar, sensibilidade ao toque.',
  'Cavities in cervical spinal cord; air scratching, touch sensitivity.',
  'watch','seed'),
('dog','Cavalier King Charles Spaniel','luxating_patella','Luxação de patela','Patellar luxation',
  'Comum em raças pequenas; claudicação intermitente.',
  'Common in small breeds; intermittent lameness.',
  'watch','seed'),
('dog','Cavalier King Charles Spaniel','eye_conditions','Problemas oculares (catarata, retina)','Eye conditions (cataract, retina)',
  'Múltiplas condições oculares; exame anual recomendado.',
  'Multiple ocular conditions; annual exam recommended.',
  'monitor','seed'),

-- 19) Pinscher Miniatura
('dog','Pinscher Miniatura','luxating_patella','Luxação de patela','Patellar luxation',
  'Frequente em toy breeds; cirurgia em graus altos.',
  'Frequent in toy breeds; surgery for higher grades.',
  'watch','seed'),
('dog','Pinscher Miniatura','legg_calve_perthes','Doença de Legg-Calvé-Perthes','Legg-Calvé-Perthes disease',
  'Necrose asséptica da cabeça do fêmur em cães jovens; claudicação.',
  'Aseptic necrosis of femoral head in young dogs; lameness.',
  'monitor','seed'),
('dog','Pinscher Miniatura','progressive_retinal_atrophy','Atrofia progressiva de retina','Progressive retinal atrophy',
  'Cegueira hereditária; teste genético disponível.',
  'Hereditary blindness; genetic test available.',
  'monitor','seed'),
('dog','Pinscher Miniatura','mucopolysaccharidosis_vi','Mucopolissacaridose VI','Mucopolysaccharidosis VI',
  'Doença de depósito lisossomal; deformidades esqueléticas.',
  'Lysosomal storage disease; skeletal deformities.',
  'monitor','seed'),

-- 20) Husky Siberiano
('dog','Husky Siberiano','hip_dysplasia','Displasia coxofemoral','Hip dysplasia',
  'Predisposição moderada; triagem recomendada.',
  'Moderate predisposition; screening recommended.',
  'watch','seed'),
('dog','Husky Siberiano','hereditary_cataracts','Catarata hereditária','Hereditary cataracts',
  'Pode surgir antes dos 2 anos; exame oftálmico periódico.',
  'May develop before age 2; periodic ophthalmic exam.',
  'watch','seed'),
('dog','Husky Siberiano','zinc_responsive_dermatosis','Dermatose responsiva ao zinco','Zinc-responsive dermatosis',
  'Lesões crostosas periorais; resposta a suplementação de zinco.',
  'Crusting perioral lesions; responds to zinc supplementation.',
  'monitor','seed'),
('dog','Husky Siberiano','hypothyroidism','Hipotireoidismo','Hypothyroidism',
  'Sinais incluem letargia, ganho de peso e alopecia.',
  'Signs include lethargy, weight gain, and alopecia.',
  'watch','seed'),

-- ============================================================
-- GATOS (10 raças)
-- ============================================================

-- 1) Persa
('cat','Persa','brachycephalic_airway','Síndrome braquicefálica','Brachycephalic airway syndrome',
  'Face achatada causa estertor e dificuldade respiratória.',
  'Flat face causes stridor and breathing difficulty.',
  'manage','seed'),
('cat','Persa','polycystic_kidney_disease','Doença renal policística (PKD)','Polycystic kidney disease',
  'Altíssima prevalência; teste genético e USG renal recomendados.',
  'Very high prevalence; genetic test and renal ultrasound recommended.',
  'manage','seed'),
('cat','Persa','dental_malocclusion','Má oclusão dentária','Dental malocclusion',
  'Mandíbula curta causa apinhamento; escovação + profilaxia.',
  'Short jaw causes crowding; brushing + cleaning.',
  'watch','seed'),
('cat','Persa','chronic_epiphora','Epífora crônica (lacrimejamento)','Chronic epiphora',
  'Conformação facial impede drenagem lacrimal normal.',
  'Facial conformation prevents normal tear drainage.',
  'manage','seed'),

-- 2) Siamês
('cat','Siamês','progressive_retinal_atrophy','Atrofia progressiva de retina','Progressive retinal atrophy',
  'Cegueira progressiva; teste genético disponível.',
  'Progressive blindness; genetic test available.',
  'watch','seed'),
('cat','Siamês','feline_asthma','Asma felina','Feline asthma',
  'Tosse e dispneia paroxísticos; broncodilatador e corticoide inalatórios.',
  'Paroxysmal cough and dyspnea; inhaled bronchodilators and steroids.',
  'manage','seed'),
('cat','Siamês','amyloidosis','Amiloidose','Amyloidosis',
  'Depósito amiloide hepático; insuficiência hepática súbita.',
  'Hepatic amyloid deposition; sudden liver failure.',
  'monitor','seed'),
('cat','Siamês','gastrointestinal_lymphoma','Linfoma gastrintestinal','GI lymphoma',
  'Raça predisposta em gatos idosos; vômitos e perda de peso.',
  'Predisposed breed in older cats; vomiting and weight loss.',
  'monitor','seed'),

-- 3) Maine Coon
('cat','Maine Coon','hypertrophic_cardiomyopathy','Cardiomiopatia hipertrófica (HCM)','Hypertrophic cardiomyopathy',
  'Mutação MYBPC3 identificada na raça; ecocardio anual após 3 anos.',
  'MYBPC3 mutation identified in the breed; annual echo after age 3.',
  'manage','seed'),
('cat','Maine Coon','hip_dysplasia','Displasia coxofemoral','Hip dysplasia',
  'Incomum em gatos mas presente na raça; claudicação posterior.',
  'Uncommon in cats but present in the breed; hindlimb lameness.',
  'watch','seed'),
('cat','Maine Coon','spinal_muscular_atrophy','Atrofia muscular espinhal','Spinal muscular atrophy',
  'Fraqueza muscular progressiva; teste genético disponível.',
  'Progressive muscle weakness; genetic test available.',
  'monitor','seed'),
('cat','Maine Coon','polycystic_kidney_disease','Doença renal policística','Polycystic kidney disease',
  'Menor incidência que Persas; triagem por USG.',
  'Lower incidence than Persians; ultrasound screening.',
  'monitor','seed'),

-- 4) Ragdoll
('cat','Ragdoll','hypertrophic_cardiomyopathy','Cardiomiopatia hipertrófica (HCM)','Hypertrophic cardiomyopathy',
  'Mutação específica R820W; ecocardio anual.',
  'Specific R820W mutation; annual echocardiogram.',
  'manage','seed'),
('cat','Ragdoll','polycystic_kidney_disease','Doença renal policística','Polycystic kidney disease',
  'Triagem por USG abdominal.',
  'Screening via abdominal ultrasound.',
  'monitor','seed'),
('cat','Ragdoll','flutd','Doença do trato urinário inferior felino (FLUTD)','Feline lower urinary tract disease',
  'Estresse e obesidade são fatores de risco; atenção a esforço ao urinar.',
  'Stress and obesity are risk factors; watch for straining to urinate.',
  'watch','seed'),
('cat','Ragdoll','obesity','Obesidade','Obesity',
  'Tendência ao ganho de peso; controle rigoroso de porções.',
  'Tendency to weight gain; strict portion control.',
  'watch','seed'),

-- 5) British Shorthair
('cat','British Shorthair','hypertrophic_cardiomyopathy','Cardiomiopatia hipertrófica (HCM)','Hypertrophic cardiomyopathy',
  'Prevalência alta; ecocardio anual a partir de 3 anos.',
  'High prevalence; annual echo from age 3.',
  'manage','seed'),
('cat','British Shorthair','polycystic_kidney_disease','Doença renal policística','Polycystic kidney disease',
  'Menor que em Persas, mas presente; USG renal de triagem.',
  'Lower than in Persians, but present; renal ultrasound screening.',
  'watch','seed'),
('cat','British Shorthair','hemophilia_b','Hemofilia B','Hemophilia B',
  'Deficiência de fator IX; teste genético em reprodutores.',
  'Factor IX deficiency; genetic test in breeding animals.',
  'monitor','seed'),
('cat','British Shorthair','obesity','Obesidade','Obesity',
  'Raça pesada e tranquila; propensa a ganho de peso.',
  'Heavy, calm breed; prone to weight gain.',
  'manage','seed'),

-- 6) Scottish Fold
('cat','Scottish Fold','osteochondrodysplasia','Osteocondrodisplasia','Scottish Fold osteochondrodysplasia',
  'Condição genética inerente; artrite e deformidades dolorosas.',
  'Inherent genetic condition; painful arthritis and deformities.',
  'manage','seed'),
('cat','Scottish Fold','hypertrophic_cardiomyopathy','Cardiomiopatia hipertrófica (HCM)','Hypertrophic cardiomyopathy',
  'Rastrear via ecocardio anual.',
  'Screen via annual echocardiogram.',
  'watch','seed'),
('cat','Scottish Fold','polycystic_kidney_disease','Doença renal policística','Polycystic kidney disease',
  'Triagem por USG recomendada.',
  'Ultrasound screening recommended.',
  'monitor','seed'),

-- 7) Sphynx
('cat','Sphynx','hypertrophic_cardiomyopathy','Cardiomiopatia hipertrófica (HCM)','Hypertrophic cardiomyopathy',
  'Alta prevalência na raça; ecocardio anual.',
  'High breed prevalence; annual echocardiogram.',
  'manage','seed'),
('cat','Sphynx','seborrhea','Dermatite seborreica','Seborrhea',
  'Pele sem pelo requer higiene específica semanal.',
  'Hairless skin requires specific weekly hygiene.',
  'manage','seed'),
('cat','Sphynx','hereditary_myopathy','Miopatia hereditária','Hereditary myopathy',
  'Fraqueza muscular; diagnóstico por biópsia muscular.',
  'Muscle weakness; diagnosis via muscle biopsy.',
  'monitor','seed'),
('cat','Sphynx','dental_disease','Doença periodontal','Periodontal disease',
  'Propensão elevada; higiene dental rigorosa.',
  'High propensity; rigorous dental hygiene.',
  'watch','seed'),

-- 8) Bengal
('cat','Bengal','hypertrophic_cardiomyopathy','Cardiomiopatia hipertrófica (HCM)','Hypertrophic cardiomyopathy',
  'Monitoramento ecocardiográfico periódico.',
  'Periodic echocardiographic monitoring.',
  'watch','seed'),
('cat','Bengal','progressive_retinal_atrophy','Atrofia progressiva de retina','Progressive retinal atrophy',
  'Forma Bengal-específica; teste genético disponível.',
  'Bengal-specific form; genetic test available.',
  'watch','seed'),
('cat','Bengal','pyruvate_kinase_deficiency','Deficiência de piruvato quinase (PK def)','Pyruvate kinase deficiency',
  'Anemia hemolítica intermitente; teste genético.',
  'Intermittent hemolytic anemia; genetic test.',
  'monitor','seed'),
('cat','Bengal','flat_chested_kitten','Síndrome do filhote peito chato','Flat-chested kitten syndrome',
  'Deformidade torácica em filhotes; pode resolver ou exigir suporte.',
  'Chest deformity in kittens; may resolve or need support.',
  'monitor','seed'),

-- 9) Norueguês da Floresta
('cat','Norueguês da Floresta','glycogen_storage_disease_iv','Glicogenose tipo IV','Glycogen storage disease IV',
  'Doença de depósito de glicogênio; teste genético em reprodutores.',
  'Glycogen storage disease; genetic test in breeding animals.',
  'monitor','seed'),
('cat','Norueguês da Floresta','hypertrophic_cardiomyopathy','Cardiomiopatia hipertrófica (HCM)','Hypertrophic cardiomyopathy',
  'Ecocardio de triagem recomendado.',
  'Screening echocardiogram recommended.',
  'watch','seed'),
('cat','Norueguês da Floresta','polycystic_kidney_disease','Doença renal policística','Polycystic kidney disease',
  'Menor incidência; USG se houver sinais renais.',
  'Lower incidence; ultrasound if renal signs present.',
  'monitor','seed'),
('cat','Norueguês da Floresta','hip_dysplasia','Displasia coxofemoral','Hip dysplasia',
  'Incomum em gatos, mas presente em raças grandes.',
  'Uncommon in cats, but present in large breeds.',
  'monitor','seed'),

-- 10) Abissínio
('cat','Abissínio','progressive_retinal_atrophy','Atrofia progressiva de retina','Progressive retinal atrophy',
  'Cegueira progressiva; teste genético disponível.',
  'Progressive blindness; genetic test available.',
  'watch','seed'),
('cat','Abissínio','pyruvate_kinase_deficiency','Deficiência de piruvato quinase (PK def)','Pyruvate kinase deficiency',
  'Anemia hemolítica episódica; teste genético.',
  'Episodic hemolytic anemia; genetic test.',
  'monitor','seed'),
('cat','Abissínio','amyloidosis','Amiloidose renal','Renal amyloidosis',
  'Insuficiência renal em gatos jovens; proteinúria inicial.',
  'Renal failure in young cats; initial proteinuria.',
  'watch','seed'),
('cat','Abissínio','periodontal_disease','Doença periodontal','Periodontal disease',
  'Alta prevalência; higiene dental regular.',
  'High prevalence; regular dental hygiene.',
  'watch','seed')

ON CONFLICT (species, breed, condition_key) DO NOTHING;

-- Conta aproximada após o seed:
-- dogs:  20 raças × ~4 condições = ~80 linhas
-- cats:  10 raças × ~4 condições = ~40 linhas
-- Total: ~120 linhas (ajustado pelo ON CONFLICT se re-rodar)
